//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperZapatosConsole
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SuperZapatosEntities2 : DbContext
    {
        public SuperZapatosEntities2()
            : base("name=SuperZapatosEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<store> stores { get; set; }
    
        public virtual int TraerTiendasId(Nullable<int> idTienda)
        {
            var idTiendaParameter = idTienda.HasValue ?
                new ObjectParameter("IdTienda", idTienda) :
                new ObjectParameter("IdTienda", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TraerTiendasId", idTiendaParameter);
        }
    
        public virtual int TraerTodasTiendas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TraerTodasTiendas");
        }
    
        public virtual ObjectResult<TraerTodosArticulos_Result> TraerTodosArticulos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraerTodosArticulos_Result>("TraerTodosArticulos");
        }
    }
}
